---
- name: Playbook to install and configure Apache web server
  hosts: all
  become: true
  tasks:
    - name: Install Apache and Php Support
      ansible.builtin.package:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: present
        update_cache: true

    - name: Ensure Apache is running and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
      when: ansible_distribution == "Ubuntu"

    - name: Change HTTPD port to 8280
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen'
        line: 'Listen 8280'
      notify: Restart_httpd
      when: ansible_distribution == "Fedora"

  handlers:
    - name: Restart_httpd
      ansible.builtin.service:
        name: httpd
        state: restarted

    - name: Ensure Httpd is running and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution == "Fedora"
